// @ts-check
// This file is automatically generated. DO NOT EDIT

/**
 * Invokes a Go method by name.
 * @param {string} methodName - The name of the method to call.
 * @param {Object} [args] - Optional arguments to pass to the method.
 * @returns {Promise<any>} - A promise that resolves with the result.
 */
export function invoke(methodName, args) {
  return window['go']['main']['App'][methodName](args)
}
