// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1) {
  return window['go']['main']['App']['AddTask'](arg1);
}

export function ClearTasks() {
  return window['go']['main']['App']['ClearTasks']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetPrinters() {
  return window['go']['main']['App']['GetPrinters']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function ProcessPrintTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ProcessPrintTask'](arg1, arg2, arg3, arg4);
}

export function ProcessPrintURLTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ProcessPrintURLTask'](arg1, arg2, arg3, arg4);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function UpdateTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2, arg3, arg4);
}
