// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTask(arg1:main.TaskInfo):Promise<void>;

export function ClearTasks():Promise<void>;

export function GetConfig():Promise<main.Config>;

export function GetPrinters():Promise<Array<main.PrinterInfo>>;

export function GetStatus():Promise<main.ServiceStatus>;

export function GetTasks():Promise<Array<main.TaskInfo>>;

export function ProcessPrintTask(arg1:string,arg2:Array<number>,arg3:string,arg4:string):Promise<void>;

export function ProcessPrintURLTask(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function StartServer():Promise<void>;

export function StopServer():Promise<void>;

export function UpdateTask(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;
